probberechts/hexo-theme-cactus

_config.yml, layout/_partial/head.ejs, layout/_partial/header.ejs
Make enable using [Gravatar](http://gravatar.com) for logo and favicon.
See [Hexo/gravatar](https://hexo.io/docs/helpers.html#gravatar).
=> Using gravitas in logo and favicon

layout/index.ejs, source/css/_partial/index.styl
=> remove ad blocking triggers on social media links

languages/es.yml
Hi, I'm using this great theme and so..I add Spanish to the lenguajes
=> Spanish languaje

_config.yml, layout/_partial/scripts.ejs
Add Baidu Analytics support for those who aren't able to access Google Service.
=> Add Baidu Analytics Support

languages/fa.yml
So I made this translation for this theme. I'm working on RTL Support after this. I'd be happy to contribute to this project.
=> Adding Persian Translations

languages/pt-br.yml
Hello!
Just added a new `.yml` file to the "languages" folder with a brazilian portuguese (pt-br) translation.
Hope it helps.
=> Added brazilian portuguese translation

layout/index.ejs
- for correct working need to add 'posts_overview' property
=> Added post_overview property

languages/it.yml
Added italian localization file
=> italian translation

README.md
Hi @probberechts! Great job with this theme! Thanks to share :+1: 
This PR add the Brazilian Portuguese `pt-br`, Catalan `ca` and Italian `it` to language list in README file.
=> Update translations list in README

source/css/_extend.styl
=> Fix table overflow CSS to add horizontal scrollbar

languages/zh-CN.yml, languages/zh-TW.yml
solve the "bad indentation" problem in zh-TW.yml
problem show:
[bad indentation](https://ws4.sinaimg.cn/large/006tKfTcgy1g0937rmdxej30vg0dsnau.jpg)
=> update zh-TW.yml & zh-CN.yml

source/css/_highlight/gruvbox-dark.styl
* Add Gruvbox Dark highlight theme
=> Add Gruvbox code highlight theme

source/css/_partial/article.styl, source/css/_partial/post/actions_desktop.styl
Fix syntax error in `#nav ul a` and `.caption`
=> Fix some syntax errors

layout/_partial/post/share.ejs
This PR adds a share link for hacker news in post sharing menu
=> Adds share link for hacker news

layout/_partial/scripts.ejs, source/css/_extend.styl, source/css/style.styl
Fix hexojs/hexo-util@401dde1621331d07ce52caf37c94951bac33ddb7 update code highlight renderer.
=> Fix highlight renderer update

README.md, languages/de.yml
=> Added german translations

languages/fr.yml
Fix and improve french translation
=> Improve french translation

source/css/_partial/post/actions_desktop.styl
Removing certain elements that hinder the rendering of the page on print.
https://github.com/probberechts/hexo-theme-cactus/issues/227
=> Fix:227 TOC Rendering on Print

README.md, _config.yml, layout/_partial/scripts.ejs
[Umami](https://umami.is) is Self-hosted analytics developed in next.js
=> Support Umami Analytics

layout/_partial/scripts.ejs
Update Google Analytics Code in `script.ejs`.
=> Update Google Analytics Code

.gitignore, languages/ar.yml
I just translated the texts to Arabic, my native language.
=> Add support for Arabic language

README.md, _config.yml, layout/_partial/head.ejs, layout/_partial/scripts.ejs
The umami analytics allow to assign a custom name to the tracker script to help avoid some ad-blockers 😈
https://umami.is/docs/environment-variables
=> Allow to change the name of umami tracker script

languages/tr.yml
The translation has been made more suitable for Turkish. Also, the problem of Arabic characters appearing on the copy tooltip has been fixed.
=> Improvements for Turkish language
