- layout/_partial/head.ejs
- layout/_partial/scripts.ejs
- layout/_partial/styles.ejs
- layout/layout.ejs
Hello,
Running Google's [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) test on cactus-dark theme shows some performance warnings about render blocking resources (both JS & CSS). 
This PR is a small change proposal to improve performance on crappy networks, by moving jquery and non-critical CSS file to the bottom of the page.
Related documentation :
- [Blocking JS](https://developers.google.com/speed/docs/insights/BlockingJS)
- [Optimize CSS Delivery](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery)
> Move render blocking JS and CSS

- source/css/_partial/post/actions_desktop.styl
Stop TOC list in sidebar on large screens from overflowing into body. 23em is what's required for no margin. 20em is what's set in this change.
> Prevent TOC overflow

- source/css/_partial/post/actions_desktop.styl
Hi, I just added a `padding-righ: 2rem;` in `actions_desktop.styl`, to get these changes:
**before:**
**after:**
> Added padding-right to: #header-post #share

- README.md
- languages/ru.yml
This should get you started! The "copyright" notice is left empty intentionally — we don't have a suitable term, and a plain copyright sign is fairy common.
Some side notes:
- The included Meslo font comes with cyrillic support, which increases load time for (the majority of sites) that don't use it.
- YYYY-MM-DD date format is uncommon in Russia, mostly DD.MM.YYYY is used.
I'm new to hexo though, can't seem a to find a way of overriding these from the locale file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/probberechts/hexo-theme-cactus/87)
> Add Russian language translation

- _config.yml
- languages/en.yml
- layout/index.ejs
I quite missed that feature in this awesome theme :). 
Added a new setting for the config to display all tags on the index page. 
This will use the hexo helperscript tagcloud().
Preview:
> Added tagcloud option to the index page

- layout/layout.ejs
This will fix the "Stray start tag" from the W3C validator.
Fixes #147
> Move css and scripts partials inside the body

- source/css/_extend.styl
On my chrome \<hr\> is rendered with zero size and 50% on both left and right, making it appears as a dot. The added line forces the rule to extends fully both sides in its containing element.
> Fix <hr> size

- layout/_partial/head.ejs
- layout/_partial/header.ejs
An error will be raised when `gravatar` area is not present in `_config.yml` of the theme. This PR check for `theme.gravatar` before invoking `theme.gravatar.email` to prevent this.
> Fix error when gravatar is not present

- layout/index.ejs
Social links are cross-origin, and rel="noopener"` or `rel="noreferrer"` must be added to any external links to improve performance and prevent security vulnerabilities.
> fix: links to cross origin destinations are unsafe

- layout/_partial/scripts.ejs
- source/js/search.js
Currently `No results found.` is always shown even if search results not empty. 
https://probberechts.github.io/hexo-theme-cactus/cactus-white/public/search/.
https://blog.yusanshi.com/search/
> Fix 'no results found' problem in search

- README.md
Replace broken link [https://hexo.io/docs/deployment](https://hexo.io/docs/deployment) by [https://hexo.io/docs/one-command-deployment.html](https://hexo.io/docs/one-command-deployment.html)
> Fix broken deploy link in readme

- layout/index.ejs
Hey thanks for a awesome theme. I realized that fa brand icons doesn't include rss feed. For rss in social media links, I just added manually (like mail ==> envolope).
> rss icon added for social media links

- README.md
- layout/_partial/head.ejs
1. Change desktop favicon size to 48, former 16x16 size looks outdated on a high-resolution screen.
2. Use corresponding nav keywords under languages/.
> Change favicon size & nav keywords

- _config.yml
- layout/_partial/head.ejs
- layout/_partial/header.ejs
#243 
Add `hash` option to `gravatar`.
Note that `gravatar.email` will come before `gravatar.hash`.
> Support for using hash on Gravatar options directly #243

- README.md
- _config.yml
- source/css/_partial/header.styl
- source/css/_variables.styl
Hey there @probberechts 
Thanks for your great theme!
I tried to add an option to turn on/off the logo grayout effect (#210). Since it seems the current merge-config script is using shadow merge, I added a `logo-grayout` option out of `logo` configs. I'm wondering if it's ok.
I'll be appreciated if you can have a look at my pr.
Thank you!
> Add logo grayout option

- layout/index.ejs
Fixed a broken link for a writing page in Home.
---
Example:
Setup the navigation menu in the `_config.yml` as follows:
```yaml
nav:
home: /
articles: /posts/
```
Then,
- Actual: The link for the writing page in Home goes to `/archives/` (so, the link is broken).
- Expected: The link goes to `/posts/`.
> Fix a broken link for writing section

- source/js/search.js
Bug: If `dataContent` contains uppercase characters, the local search does not match it since `indexOf` is case-sensitive.
Fixed it.
> Fix local search for uppercases

- _config.yml
- layout/_partial/head.ejs
Added support for latex to display complex equations.
btw: Because the use of plugins may lead to too many theme changes, online loading plug-ins are used here. Users can close in _config.xml as needed.
> feature: add mathJax support for latex

- source/css/_partial/post/actions_desktop.styl
- source/js/main.js
A minor bug related to the top menu.
Because the `#menu` uses `visibility: hidden` instead of `display: none`, it will always occupy the space on top of the main body. Then the width of it is large enough (due to long `#nav`) to block interactive elements under it. In the following case, copy button of the code block is not clickable.
p.s. In normal case this won't matter because `#nav` will be set to `display: none` when scrolling to post content. I found this issue when I was doing a refresh.
> Fix hidden menu bug

- source/css/_colors/classic.styl
- source/css/_colors/dark.styl
- source/css/_colors/light.styl
- source/css/_colors/white.styl
- source/css/style.styl
Use [`scrollbar`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars) for Firefox and [`::-webkit-scrollbar`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) for other browsers. Neither is stable and MDN suggests not using them in production; but since no standard solution exists at all let's just use them for now :P
All scrollbars including the vertical one for the whole page and those for code blocks are affected. Below are the effects:
- Dark
- Light
- Classic
- White
Tested only on Firefox and Chromium. Should have similar effects on most popular browsers according to MDN's compatibility table.
This should close #273.
> Customize scrollbar style

- README.md
I am new to hexo, so I had problems setting up the template for the first time.
After reading the description of another hexo template I realized, the description of the installation process omitted two steps, which i added with https://github.com/probberechts/hexo-theme-cactus/commit/6d2dc29671123f22dac3a9569306da6e53aca7c0
I also fixed some minor typos and unified the formatting.
> Improve readme description

- README.md
- The example shown in README for utterances config uses the wrong key ( `utteranc` instead of `utterances`)
> Fix wrong utterances example config

- _config.yml
- layout/404.ejs
- scripts/errror_404.js
As #290 mentioned, theme-cactus lacks support for generating a 404 page, which is not visitor-friendly.
I added a simple 404-page generating feature that only shows visitors a customized title and description text.
> Add 404 Page Generating Support

- layout/index.ejs
Hello 👋 
Here is a super simple change to add support for `rel="me"` micro-format. It's especially useful for Mastodon users as it allows [profile link verification](https://docs.joinmastodon.org/user/profile/#verification) on that platform. 
According to [micro-formats specification](https://microformats.org/wiki/rel-me), it can be used "_on any hyperlinks from one page about a person to other pages about that same person_", so I added it on every `social_links`.
Best ^^
> Add support for `rel="me"` microformat for `social_links`

- gulpfile.js
- package.json
[gulp-download](https://www.npmjs.com/package/gulp-download) has not been updated since 9 years!
It contains [gulp-util](https://www.npmjs.com/package/gulp-util), which has been [deprecated](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5).
I looked for alternatives and believe that [gulp-download-stream](https://www.npmjs.com/package/gulp-download-stream) is sufficient.
* The dependency is currently still maintained (last published 4 months ago)
* From the documented usage in the `README`-file the behaviour seems to be the same as the other dependency
`gulp-util` contains dependencies, which might contain security issues (I am no expert!)
Replacing this indeed removes a lot of lodash dependencies and `npm install` shows that the change removes one **critical** issue:
**Before**
`found …
> Replace gulp-download with gulp-download-stream

- layout/_partial/header.ejs
- layout/_partial/post/date.ejs
- layout/_partial/post/tag.ejs
- layout/_partial/post/title.ejs
- layout/index.ejs
- layout/layout.ejs
- layout/post.ejs
- source/css/_partial/header.styl
Hello 👋 
This PR intent to improve support for [microformat2](https://microformats.org/wiki/microformats2) in the markup. 
I mostly ran the validator available on [IndieWebify.Me](https://indiewebify.me/) (See _"Publishing on the IndieWeb Level 2 / 1. Mark up your content"_ section) and followed instructions to fix/improve support. 
Adds support for [`h-card`](https://microformats.org/wiki/h-card) on the home page, and [`h-entry`](http://microformats.org/wiki/h-entry) in the post layout. More details bellow.
I did it for my own usage, and I guess it might be useful to other people as well. 
Best ^^
`h-card` is used to identify the website owner. 
I added support for the following microformats:
- `h-card` : Main container
- `u-url` : website URL (or links to other URL representing the …
> Better support for Microformats

- layout/_partial/google_analytics.ejs
- layout/_partial/head.ejs
- layout/_partial/scripts.ejs
Accroding to the [guide](https://developers.google.com/analytics/devguides/collection/gtagjs?hl=en#install_the_google_tag), the google analytics code should be put after the `<head>`, the current code puts this in the `<body>`, which is not correct, so this commits does two things to fix this:
+ add a new template file called `google_analytics.ejs` to move the logic from `scripts.ejs`.
+ add a new line in `head.ejs` to incorporate `google_analytics.ejs`.
> fix(google analytics): put the analytics in the <head>

- layout/archive.ejs
- source/css/style.styl
Fixed NaN error message in archive.ejs. Particularly shown in archive page.
**Image before fixing the bug**
**Image after fixing the bug**
In addition, fixed span#actions element direction for RTL languages. The direction does not need to be changed, the current styling after making the theme's direction RTL by using RTL languages messes up the action element as shown in following pictures.
**Before fixing span#actions**
**After fixing span#actions**
The bug is successfully fixed and it has been tested for RTL languages(Persian language) as shown in the pictures above.
> Fixed NaN error in archive.ejs

- source/css/style.styl
`font-display` is a `@font-face` rule, and `flex` is not applied under a flex layout context. Both rules are invalid.
> Remove invalid css rules
